'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Hotel_All1

    '''<summary>
    '''Literal_Hotel_NameTaB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal_Hotel_NameTaB As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Literal_Hotel_DataInside control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal_Hotel_DataInside As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Literal_GPS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal_GPS As Global.System.Web.UI.WebControls.Literal
End Class
