'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Tradition_All1

    '''<summary>
    '''Literal_Tradition1_NameTaB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal_Tradition1_NameTaB As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Literal_Tradition1_DataInside control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal_Tradition1_DataInside As Global.System.Web.UI.WebControls.Literal
End Class
