<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="AboutTakDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AboutTak" Member="AboutTaks">
    <Type Name="AboutTak">
      <Column Name="AboutTak_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AboutTak_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AboutTak_Details" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AboutTak_Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>