<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DataClassesTakDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Table]" Member="Tables">
    <Type Name="Table">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_username" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="user_password" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="user_type" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="user_FnameLname" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="user_phonenumber" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
    </Type>
  </Table>
</Database>