<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="HomeClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Home_Product" Member="Home_Products">
    <Type Name="Home_Product">
      <Column Name="Product_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Product_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Product_Details" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Product_Link" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Product_Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Home_Traveling" Member="Home_Travelings">
    <Type Name="Home_Traveling">
      <Column Name="Travel_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Travel_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Travel_Details" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Travel_Link" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Travel_Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Travel_Slide" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Home_History" Member="Home_Histories">
    <Type Name="Home_History">
      <Column Name="History_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="History_Form" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="History_Date" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>