'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Database1")>  _
Partial Public Class ProductListDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertProduct(instance As Product)
    End Sub
  Partial Private Sub UpdateProduct(instance As Product)
    End Sub
  Partial Private Sub DeleteProduct(instance As Product)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("Database1ConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property Products() As System.Data.Linq.Table(Of Product)
		Get
			Return Me.GetTable(Of Product)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Product")>  _
Partial Public Class Product
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _Product_ID As Integer
	
	Private _Product_Name As String
	
	Private _Product_Details As String
	
	Private _Product_Type As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnProduct_IDChanging(value As Integer)
    End Sub
    Partial Private Sub OnProduct_IDChanged()
    End Sub
    Partial Private Sub OnProduct_NameChanging(value As String)
    End Sub
    Partial Private Sub OnProduct_NameChanged()
    End Sub
    Partial Private Sub OnProduct_DetailsChanging(value As String)
    End Sub
    Partial Private Sub OnProduct_DetailsChanged()
    End Sub
    Partial Private Sub OnProduct_TypeChanging(value As String)
    End Sub
    Partial Private Sub OnProduct_TypeChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Product_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property Product_ID() As Integer
		Get
			Return Me._Product_ID
		End Get
		Set
			If ((Me._Product_ID = value)  _
						= false) Then
				Me.OnProduct_IDChanging(value)
				Me.SendPropertyChanging
				Me._Product_ID = value
				Me.SendPropertyChanged("Product_ID")
				Me.OnProduct_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Product_Name", DbType:="NVarChar(MAX)")>  _
	Public Property Product_Name() As String
		Get
			Return Me._Product_Name
		End Get
		Set
			If (String.Equals(Me._Product_Name, value) = false) Then
				Me.OnProduct_NameChanging(value)
				Me.SendPropertyChanging
				Me._Product_Name = value
				Me.SendPropertyChanged("Product_Name")
				Me.OnProduct_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Product_Details", DbType:="NVarChar(MAX)")>  _
	Public Property Product_Details() As String
		Get
			Return Me._Product_Details
		End Get
		Set
			If (String.Equals(Me._Product_Details, value) = false) Then
				Me.OnProduct_DetailsChanging(value)
				Me.SendPropertyChanging
				Me._Product_Details = value
				Me.SendPropertyChanged("Product_Details")
				Me.OnProduct_DetailsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Product_Type", DbType:="NVarChar(MAX)")>  _
	Public Property Product_Type() As String
		Get
			Return Me._Product_Type
		End Get
		Set
			If (String.Equals(Me._Product_Type, value) = false) Then
				Me.OnProduct_TypeChanging(value)
				Me.SendPropertyChanging
				Me._Product_Type = value
				Me.SendPropertyChanged("Product_Type")
				Me.OnProduct_TypeChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
