'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="userSQL")>  _
Partial Public Class DataClasses1DataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertTable(instance As Table)
    End Sub
  Partial Private Sub UpdateTable(instance As Table)
    End Sub
  Partial Private Sub DeleteTable(instance As Table)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("userSQLConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property Tables() As System.Data.Linq.Table(Of Table)
		Get
			Return Me.GetTable(Of Table)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.[Table]")>  _
Partial Public Class Table
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _user_email As String
	
	Private _user_password As String
	
	Private _user_type As String
	
	Private _user_birthdate As String
	
	Private _user_phonenumber As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub Onuser_emailChanging(value As String)
    End Sub
    Partial Private Sub Onuser_emailChanged()
    End Sub
    Partial Private Sub Onuser_passwordChanging(value As String)
    End Sub
    Partial Private Sub Onuser_passwordChanged()
    End Sub
    Partial Private Sub Onuser_typeChanging(value As String)
    End Sub
    Partial Private Sub Onuser_typeChanged()
    End Sub
    Partial Private Sub Onuser_birthdateChanging(value As String)
    End Sub
    Partial Private Sub Onuser_birthdateChanged()
    End Sub
    Partial Private Sub Onuser_phonenumberChanging(value As String)
    End Sub
    Partial Private Sub Onuser_phonenumberChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_user_email", DbType:="NChar(40) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property user_email() As String
		Get
			Return Me._user_email
		End Get
		Set
			If (String.Equals(Me._user_email, value) = false) Then
				Me.Onuser_emailChanging(value)
				Me.SendPropertyChanging
				Me._user_email = value
				Me.SendPropertyChanged("user_email")
				Me.Onuser_emailChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_user_password", DbType:="NChar(20)")>  _
	Public Property user_password() As String
		Get
			Return Me._user_password
		End Get
		Set
			If (String.Equals(Me._user_password, value) = false) Then
				Me.Onuser_passwordChanging(value)
				Me.SendPropertyChanging
				Me._user_password = value
				Me.SendPropertyChanged("user_password")
				Me.Onuser_passwordChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_user_type", DbType:="NChar(10)")>  _
	Public Property user_type() As String
		Get
			Return Me._user_type
		End Get
		Set
			If (String.Equals(Me._user_type, value) = false) Then
				Me.Onuser_typeChanging(value)
				Me.SendPropertyChanging
				Me._user_type = value
				Me.SendPropertyChanged("user_type")
				Me.Onuser_typeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_user_birthdate", DbType:="NChar(10)")>  _
	Public Property user_birthdate() As String
		Get
			Return Me._user_birthdate
		End Get
		Set
			If (String.Equals(Me._user_birthdate, value) = false) Then
				Me.Onuser_birthdateChanging(value)
				Me.SendPropertyChanging
				Me._user_birthdate = value
				Me.SendPropertyChanged("user_birthdate")
				Me.Onuser_birthdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_user_phonenumber", DbType:="NChar(20)")>  _
	Public Property user_phonenumber() As String
		Get
			Return Me._user_phonenumber
		End Get
		Set
			If (String.Equals(Me._user_phonenumber, value) = false) Then
				Me.Onuser_phonenumberChanging(value)
				Me.SendPropertyChanging
				Me._user_phonenumber = value
				Me.SendPropertyChanged("user_phonenumber")
				Me.Onuser_phonenumberChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
